# https://github.com/keras-team/keras-cv/blob/master/.devcontainer/Dockerfile //example of Dockerfile used by KerasCV team
FROM mcr.microsoft.com/vscode/devcontainers/python:3.9
COPY setup.sh /setup.sh